mocked: false

mongo:
  host: localhost
  port: 27017
  username: admin
  password: XS3ms9R3tP
  database: dlabdb

securityService:
  protocol: http
  host: localhost
  port: 8090
  jerseyClient:
    timeout: 10s
    connectionTimeout: 10s

provisioningService:
  protocol: http
  host: localhost
  port: 8084
  jerseyClient:
    timeout: 3s
    connectionTimeout: 3s

server:
  rootPath: "/api"
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.epam: DEBUG
  appenders:
#    - type: console
    - type: file
      currentLogFilename: /tmp/dlab/log/selfservice.log
      archivedLogFilenamePattern: /tmp/dlab/log/selfservice-%d.log